# symbols.py

SYMBOLS = (
    "AUDCAD", "AUDCHF", "AUDJPY", "AUDNZD", "AUDSGD", "AUDUSD",
    "CADCHF", "CADJPY", "CHFJPY", "CHFSGD",
    "EURAUD", "EURCAD", "EURCHF", "EURCZK", "EURGBP", "EURJPY", "EURNOK", "EURNZD", "EURPLN", "EURSEK", "EURSGD", "EURTRY", "EURUSD", "EURZAR",
    "GBPAUD", "GPBCAD", "GPBCHF", "GPBJPY", "GBPNOK", "GBPNZD", "GBPSEK", "GBPUSD",
    "NOKSEK",
    "NZDCAD", "NZDJPY", "NZDUSD",
    "SEKJPY",
    "SGDJPY",
    "USDCAD", "USDCHF", "USDCNH", "USDCZK", "USDJPY", "USDNOK", "USDSEK", "USDSGD", "USDTHB", "USDTRY", "USDZAR",
    "ZARJPY",
    "BTCUSD", "XAGUSD", "XAUUSD",
    "DE30", "FR40", "US100", "US500", "US2000", "US30", "JP225", "IND50", "CN50U", "HKG50",
    "BRENT", "UKOil", "NGas", "US30cash-1", "US2000-1", "D30"
)



