from cred.cred import TARGET_COMP_ID, SENDER_COMP_ID_FOR_MARKET_DATA, USERNAME, PASSWORD

# Define constants for SENDER_COMP_ID and TARGET_COMP_ID
SENDER_COMP_ID = SENDER_COMP_ID_FOR_MARKET_DATA
TARGET_COMP_ID = TARGET_COMP_ID

# Define constants for USERNAME and PASSWORD
USERNAME = USERNAME
PASSWORD = PASSWORD

print(SENDER_COMP_ID)
print(TARGET_COMP_ID)
print(USERNAME)
print(PASSWORD)